### ISSUE TITLE
Decorate API-endpoints with ITKAcl decorator

### ISSUE THREAD

**Issue by NikZy** [Fotogjengen/fg#54]
<a href="https://github.com/Mikkel94"><img src="https://avatars1.githubusercontent.com/u/22194628?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Mikkel94](https://github.com/Mikkel94)**
_Sunday Sep 02, 2018 at 16:06 GMT_
_Originally opened as https://github.com/Samfundet/fg/issues/70_

----

All views in /fg/api/views.py needs to be decorated with the correct ACLs.

**Comment by NikZy** [comment]
<a href="https://github.com/Mikkel94"><img src="https://avatars1.githubusercontent.com/u/22194628?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mikkel94](https://github.com/Mikkel94)**
_Sunday Sep 02, 2018 at 16:06 GMT_

----

Depends upon #69

**Comment by carrosa** [comment]
This is done, we are checking ITKACL in the permissions file that that api viewpoints depends on.
